api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('product/cart/quantity/update/', views.product_cart_quantity_update, name='product_cart_quantity_update'),

    path('chat/message/create/', views.chat_message_create, name='chat_message_create'),
    path('chat/message/read/', views.chat_message_read, name='chat_message_read'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('login-register/', views.login_register, name='login_register'),
    path('logout/', views.auth_logout, name='auth_logout'),

    path('product/cart/', views.product_cart, name='product_cart'),
    path('product/cart/add/<product_id>/', views.product_cart_add, name='product_cart_add'),
    path('product/cart/delete/<cart_id>/', views.product_cart_delete, name='product_cart_delete'),

    path('product/checkout/', views.product_checkout, name='product_checkout'),

    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('products/', views.products, name='products'),
    path('products/<page>/', views.products, name='products'),
    path('product/review/create/<product_id>/', views.product_review_create, name='product_review_create'),
    path('product/<product_slug>/', views.product_detail, name='product_detail'),

    path('account/users/', views.account_user_list, name='account_user_list'),
    path('account/user/edit/<user_id>/', views.account_user_edit, name='account_user_edit'),
    path('account/user/delete/<user_id>/', views.account_user_delete, name='account_user_delete'),
    path('account/user/role/edit/<user_id>/<action>/', views.account_user_role_edit, name='account_user_role_edit'),
    path('account/orders/', views.account_order_list, name='account_order_list'),
    path('account/order/payment/', views.account_order_payment, name='account_order_payment'),
    path('account/order/payment/return/', views.account_order_payment_return, name='account_order_payment_return'),
    path('account/order/<order_id>/', views.account_order_detail, name='account_order_detail'),
    path('account/order/shipped/<order_id>/', views.account_order_shipped, name='account_order_shipped'),
    path('account/bulk/order/list/', views.account_bulk_order_list, name='account_bulk_order_list'),
    path('account/bulk/order/list/<manufacturer_username>/', views.account_bulk_order_list, name='account_bulk_order_list'),
    path('account/products/', views.account_product_list, name='account_product_list'),
    path('account/product/create/', views.account_product_create, name='account_product_create'),
    path('account/product/edit/<product_id>/', views.account_product_edit, name='account_product_edit'),
    path('account/product/delete/<product_id>/', views.account_product_delete, name='account_product_delete'),
    path('account/product/status/edit/<product_id>/<action>/', views.account_product_status_edit, name='account_product_status_edit'),
    path('account/profile/', views.account_profile, name='account_profile'),
    path('account/payout/', views.account_payout, name='account_payout'),
    path('account/messages/', views.account_message_list, name='account_message_list'),
    path('account/message/<username>/', views.account_message_detail, name='account_message_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.contrib.auth.decorators import login_required
from .decorators import only_anonymous, only_admin, only_in
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from django.db.models import Q, Avg, Sum, F, Prefetch
from .models import Brand, Category, Product, ProductReview, ProductCart, ProductOrder, ChatRoom, ChatMessage
from django.core.paginator import Paginator
from django.conf import settings
from django.utils.text import slugify
import urllib
import json
from utils.stripe import create_account, create_account_link, delete_account, retrieve_account, create_payment, retrieve_payment


User = get_user_model()

# start: Authentication
@only_anonymous
def login_register(request):
    next = request.GET.get('next')
    if request.method == 'POST':
        if 'register' in request.POST:
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')
            agree = request.POST.get('agree')
            manufacturer = request.POST.get('manufacturer')
            if not username:
                messages.error(request, 'Username is required.')
            elif not email:
                messages.error(request, 'Email is required.')
            elif not password:
                messages.error(request, 'Password is required.')
            elif not agree:
                messages.error(request, 'You must agree to the terms first.')
            if not agree or not username or not email or not password:
                return redirect('core:login_register')
            if User.objects.filter(Q(username=username) | Q(email=email)).exists():
                messages.error(request, 'Username or email is taken.')
                return redirect('core:login_register')
            user = User.objects.create_user(username=username, email=email, password=password)
            user.is_active = False
            if manufacturer:
                user.role = 'manufacturer'
            user.save()
            messages.success(request, 'Account created successfully. Please wait for approval.')
            return redirect('core:login_register')
        elif 'login' in request.POST:
            username = request.POST.get('username')
            password = request.POST.get('password')
            if not username:
                messages.error(request, 'Username is required.')
            elif not password:
                messages.error(request, 'Password is required.')
            if not username or not password:
                return redirect('core:login_register')
            if not User.objects.filter(username=username).exists():
                messages.error(request, 'Account does not exist.')
                return redirect('core:login_register')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if not user.is_active:
                    messages.error(request, 'Account is not active.')
                    return redirect('core:login_register')
                login(request, user)
                return redirect(next) if next else redirect('core:home')
            else:
                messages.error(request, 'Invalid credentials.')
                return redirect('core:login_register')
    return render(request, 'authentication/login-register.html')

def auth_logout(request):
    logout(request)
    return redirect('core:login_register')
# end: Authentication

# start: General
def home(request):
    products = Product.objects.filter(status='published').annotate(rating_avg=Avg('productreview__rating', default=0))
    context = {
        'products': {
            'popular': products.order_by('?')[:8],
            'new': products.order_by('-created_at')[:8],
            'hero': products.order_by('-created_at')[:4],
        }
    }
    return render(request, 'home.html', context=context)

def products(request, page=None):
    search = request.GET.get('search', '')
    category = request.GET.get('category')
    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')
    filter = Q(name__icontains=search) | Q(description__icontains=search) | Q(brand__name__icontains=search) | Q(category__name__icontains=search)
    if category:
        filter &= Q(category__slug=category)
    if price_min:
        try:
            price_min = float(price_min)
            if price_min < 0:
                messages.error(request, 'Price min must be greater than or equal to 0.')
                return redirect('core:products')
            filter &= Q(price__gte=price_min)
        except:
            messages.error(request, 'Price min must be a number.')
            return redirect('core:products')
    if price_max:
        try:
            price_max = float(price_max)
            if price_max < 0:
                messages.error(request, 'Price max must be greater than or equal to 0.')
                return redirect('core:products')
            filter &= Q(price__lte=price_max)
        except:
            messages.error(request, 'Price max must be a number.')
            return redirect('core:products')
    products_paginator = Paginator(Product.objects.annotate(rating_avg=Avg('productreview__rating', default=0)).filter(status='published').filter(filter).order_by('-created_at'), 10)
    products = products_paginator.get_page(page)
    context = {
        'products': {
            'list': products,
            'popular': Product.objects.filter(status='published').order_by('?')[:8],
        },
        'categories': Category.objects.all(),
        'brands': Brand.objects.all(),
        'params': '?'+urllib.parse.urlencode(request.GET) if search else ''
    }
    return render(request, 'products.html', context=context)

def product_detail(request, product_slug):
    product = get_object_or_404(Product, slug=product_slug, status='published')
    rating_avg = product.productreview_set.aggregate(Avg('rating', default=0))['rating__avg']
    context = {
        'product': product,
        'rating_avg': rating_avg,
        'categories': Category.objects.all()[:6],
        'products': {
            'popular': Product.objects.filter(status='published').exclude(id=product.id).order_by('?')[:8],
            'similar': Product.objects.filter(status='published').annotate(rating_avg=Avg('productreview__rating', default=0)).filter(category=product.category).exclude(id=product.id)[:8],
        },
        'reviews': ProductReview.objects.select_related('user').filter(product=product).order_by('-created_at')
    }
    return render(request, 'product-detail.html', context=context)

@login_required
@only_in(['owner'])
def product_review_create(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        rating = request.POST.get('rating')
        comment = request.POST.get('comment')
        if not rating or not comment:
            messages.error(request, 'All fields are required.')
            return redirect('core:product_detail', product_slug=product.slug)
        try:
            rating = int(rating)
            if rating < 1 or rating > 5:
                messages.error(request, 'Rating must be between 1 and 5.')
                return redirect('core:product_detail', product_slug=product.slug)
        except:
            messages.error(request, 'Rating must be a number.')
            return redirect('core:product_detail', product_slug=product.slug)
        ProductReview.objects.create(
            user=request.user,
            product=product,
            rating=rating,
            comment=comment
        )
        messages.success(request, 'Review created successfully.')
    return redirect('core:product_detail', product_slug=product.slug)

@login_required
@only_in(['owner'])
def product_cart(request):
    context = {
        'carts': ProductCart.objects.select_related('product').filter(user=request.user, order=None).annotate(total=F('quantity') * F('product__price')).order_by('-created_at'),
        'total': ProductCart.objects.filter(user=request.user, order=None).annotate(total=F('quantity') * F('product__price')).aggregate(Sum('total'))['total__sum']
    }
    return render(request, 'product-cart.html', context=context)

@login_required
@only_in(['owner'])
def product_cart_add(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    next = request.GET.get('next')
    if request.method == 'POST':
        quantity = request.POST.get('quantity')
        if not quantity:
            messages.error(request, 'Quantity is required.')
            return redirect(next) if next else redirect('core:product_detail', product_slug=product.slug)
        try:
            quantity = int(quantity)
            if quantity < 1:
                messages.error(request, 'Quantity must be greater than or equal to 1.')
                return redirect(next) if next else redirect('core:product_detail', product_slug=product.slug)
        except:
            messages.error(request, 'Quantity must be a number.')
            return redirect(next) if next else redirect('core:product_detail', product_slug=product.slug)
        if product.stock == 'out_of_stock':
            messages.error(request, 'Product is out of stock.')
            return redirect(next) if next else redirect('core:product_detail', product_slug=product.slug)
        if ProductCart.objects.filter(user=request.user, product=product, order=None).exists():
            messages.error(request, 'Product already in cart.')
            return redirect(next) if next else redirect('core:product_detail', product_slug=product.slug)
        if ProductCart.objects.filter(user=request.user, order=None).exists():
            product_cart = ProductCart.objects.filter(user=request.user, order=None).first()

core/templates/contact.html
{% extends 'base.html' %}

{% load static %}



{% block content %}
<!-- Breadcrumb Area -->
<div class="tm-breadcrumb-area tm-padding-section bg-grey" data-bgimage="{% static 'assets/images/breadcrumb-bg.jpg' %}">
    <div class="container">
        <div class="tm-breadcrumb">
            <h2>Contact Us</h2>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li>About</li>
            </ul>
        </div>
    </div>
</div>
<!--// Breadcrumb Area -->

<!-- Page Content -->
<main class="page-content">

    <!-- Contact Area -->
    <div class="tm-section tm-contact-area tm-padding-section bg-white">
        <div class="container">
            <div class="tm-contact-blocks">
                <div class="row mt-30-reverse justify-content-center">

                    <!-- Contact block -->
                    <div class="col-lg-4 col-md-6  mt-30">
                        <div class="tm-contact-block text-center">
                            <i class="ion-android-call"></i>
                            <h6>Call Us</h6>
                            <p>Phone : <a href="tel:+18009156270">1 800 915 6270</a></p>
                            <p>Tel : <a href="tel:+15147332010">1 514 733 2010</a></p>
                        </div>
                    </div>
                    <!--// Contact block -->

                    <!-- Contact block -->
                    <div class="col-lg-4 col-md-6  mt-30">
                        <div class="tm-contact-block text-center">
                            <i class="ion-location"></i>
                            <h6>Our Location</h6>
                            <p>7415 Transcanadienne, Suite 100 St. Laurent, Quebec, Canada H45T 1Z22</p>
                        </div>
                    </div>
                    <!--// Contact block -->

                    <!-- Contact block -->
                    <div class="col-lg-4 col-md-6  mt-30">
                        <div class="tm-contact-block text-center">
                            <i class="ion-email"></i>
                            <h6>Email</h6>
                            <p><a href="mailto:surose@gmail.com">surose@gmail.com</a></p>
                            <p><a href="mailto:info@surose.com">info@surose.com</a></p>
                        </div>
                    </div>
                    <!--// Contact block -->

                </div>
            </div>

        </div>
    </div>
    <!--// Contact Area -->

</main>
<!--// Page Content -->
{% endblock content %}
    

core/templates/product-cart.html
{% extends 'base.html' %}

{% load static %}



{% block content %}
<!-- Breadcrumb Area -->
<div class="tm-breadcrumb-area tm-padding-section bg-grey" data-bgimage="{% static 'assets/images/breadcrumb-bg.jpg' %}">
    <div class="container">
        <div class="tm-breadcrumb">
            <h2>Shopping Cart</h2>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="products.html">Shop</a></li>
                <li>Shopping Cart</li>
            </ul>
        </div>
    </div>
</div>
<!--// Breadcrumb Area -->

<!-- Page Content -->
<main class="page-content">

    <!-- Shopping Cart Area -->
    <div class="tm-section shopping-cart-area bg-white tm-padding-section">
        <div class="container">

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div class="alert alert-success mb-4">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-danger mb-4">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <!-- Shopping Cart Table -->
            <div class="tm-cart-table table-responsive">
                <table class="table table-bordered mb-0">
                    <thead>
                        <tr>
                            <th class="tm-cart-col-image" scope="col">Image</th>
                            <th class="tm-cart-col-productname" scope="col">Product</th>
                            <th class="tm-cart-col-price" scope="col">Price</th>
                            <th class="tm-cart-col-quantity" scope="col">Quantity</th>
                            <th class="tm-cart-col-total" scope="col">Total</th>
                            <th class="tm-cart-col-remove" scope="col">Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart in carts %}
                        <tr data-cart-id="{{ cart.id }}">
                            <td>
                                <a href="{% url 'core:product_detail' cart.product.slug %}" class="tm-cart-productimage">
                                    <img src="{{ cart.product.image.url }}"
                                        alt="{{ cart.product.name }} image">
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'core:product_detail' cart.product.slug %}" class="tm-cart-productname">{{ cart.product.name }}</a>
                            </td>
                            <td class="tm-cart-price">&dollar;{{ cart.product.price }}</td>
                            <td>
                                <div class="tm-quantitybox">
                                    <input type="text" value="{{ cart.quantity }}">
                                </div>
                            </td>
                            <td>
                                <span class="tm-cart-totalprice" data-cart-item-total="{{ cart.id }}">&dollar;{{ cart.total|floatformat:'2' }}</span>
                            </td>
                            <td>
                                <a href="{% url 'core:product_cart_delete' cart.id %}" onclick="return confirm('Are you sure?')" class="tm-cart-removeproduct text-dark"><i class="ion-close"></i></a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="6">No product</td>
                        </tr>
                        {% endfor %}
                        {% if carts %}
                        <tr>
                            <th colspan="4" class="text-left">Total</th>
                            <th colspan="2" class="h5" data-cart-total>&dollar;{{ total|floatformat:'2' }}</th>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
            <!--// Shopping Cart Table -->

            <!-- Shopping Cart Content -->
            <div class="tm-cart-bottomarea">
                <div class="row">
                    <div class="col-lg-8 col-md-6">
                        <div class="tm-buttongroup">
                            <a href="{% url 'core:products' %}" class="tm-button">Continue Shopping</a>
                            {% if carts %}
                            <a href="{% url 'core:product_checkout' %}" class="tm-button">Proceed To Checkout</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <!--// Shopping Cart Content -->

        </div>
    </div>
    <!--// Shopping Cart Area -->

</main>
<!--// Page Content -->
{% endblock content %}



{% block script %}
<script>
    $(document).ready(function () {
        var currentReq;
        $('.tm-quantitybox input').on('change input', function () {
            var quantity = $(this).val();
            if(!quantity) return
            var cart_id = $(this).closest('tr').attr('data-cart-id');
            currentReq = $.ajax({
                url: "{% url 'api:product_cart_quantity_update' %}",
                method: "POST",
                headers: {
                    'X-CSRFToken': getCookie('csrftoken')
                },
                data: {
                    'cart_id': cart_id,
                    'quantity': quantity,
                },
                beforeSend: function () {
                    if(currentReq) {
                        currentReq.abort();
                    }
                },
                success: function (data) {
                    if (data.success) {
                        $('[data-cart-item-total="'+cart_id+'"]').html('&dollar;'+data.total);
                        $('[data-cart-total]').html('&dollar;'+data.total_cart);
                    }
                }
            });
        });
    });

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>
{% endblock script %}

core/templates/product-checkout.html
{% extends 'base.html' %}

{% load static %}



{% block content %}
<!-- Breadcrumb Area -->
<div class="tm-breadcrumb-area tm-padding-section bg-grey" data-bgimage="{% static 'assets/images/breadcrumb-bg.jpg' %}">
    <div class="container">
        <div class="tm-breadcrumb">
            <h2>Checkout</h2>
            <ul>
                <li><a href="index.html">Home</a></li>
                <li><a href="products.html">Shop</a></li>
                <li>Checkout</li>
            </ul>
        </div>
    </div>
</div>
<!--// Breadcrumb Area -->

<!-- Page Content -->
<main class="page-content">

    <!-- Checkout Area -->
    <div class="tm-section tm-checkout-area bg-white tm-padding-section">
        <div class="container">
            <form class="tm-form tm-checkout-form" method="post">
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div class="alert alert-success mb-4">{{ message }}</div>
                        {% else %}
                            <div class="alert alert-danger mb-4">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <div class="row">
                    <div class="col-lg-6">
                        <h4 class="small-title">BILLING INFORMATION</h4>

                        <!-- Billing Form -->
                        <div class="tm-checkout-billingform">
                            <div class="tm-form-inner">
                                <div class="tm-form-field tm-form-fieldhalf">
                                    <label for="billingform-firstname">First name*</label>
                                    <input type="text" name="first_name" id="billingform-firstname">
                                </div>
                                <div class="tm-form-field tm-form-fieldhalf">
                                    <label for="billingform-lastname">Last name*</label>
                                    <input type="text" name="last_name" id="billingform-lastname">
                                </div>
                                <div class="tm-form-field">
                                    <label for="billingform-email">Email address</label>
                                    <input type="email" name="email" id="billingform-email">
                                </div>
                                <div class="tm-form-field">
                                    <label for="billingform-phone">Phone (Optional)</label>
                                    <input type="text" name="phone" id="billingform-phone">
                                </div>
                                <div class="tm-form-field">
                                    <label for="billingform-country">Country</label>
                                    <select name="country" id="billingform-country">
                                        <option value="" disabled selected>Select country</option>
                                        {% for country in countries %}   
                                        <option value="{{ country.name }}">{{ country.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="tm-form-field">
                                    <label for="billingform-address">Address</label>
                                    <input type="text" id="billingform-address" name="address"
                                        placeholder="Apartment, Street Address">
                                </div>
                                <div class="tm-form-field tm-form-fieldhalf">
                                    <label for="billingform-streetaddress">State</label>
                                    <input type="text" name="state" id="billingform-streetaddress">
                                </div>
                                <div class="tm-form-field tm-form-fieldhalf">
                                    <label for="billingform-zipcode">Zip / Postcode</label>
                                    <input type="text" name="postcode" id="billingform-zipcode">
                                </div>
                            </div>
                        </div>
                        <!--// Billing Form -->

                    </div>
                    <div class="col-lg-6">
                        <div class="tm-checkout-orderinfo">
                            <div class="table-responsive">
                                <table class="table table-borderless tm-checkout-ordertable">
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for cart in carts %}
                                        <tr>
                                            <td>{{ cart.product.name }} * {{ cart.quantity }}</td>
                                            <td>&dollar;{{ cart.total|floatformat:'2' }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                        <tr class="tm-checkout-subtotal">
                                            <td>Cart Subtotal</td>
                                            <td>&dollar;{{ subtotal|floatformat:'2' }}</td>
                                        </tr>
                                        <tr class="tm-checkout-shipping">
                                            <td>(+) Shipping Charge</td>
                                            <td>&dollar;{{ ship_charge|floatformat:'2' }}</td>
                                        </tr>
                                        <tr class="tm-checkout-total">
                                            <td>Total</td>
                                            <td>&dollar;{{ total|floatformat:'2' }}</td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <div class="tm-checkout-submit">
                                <p>Your personal data will be used to process your order, support your
                                    experience throughout this website, and for other purposes described in our
                                    privacy policy.</p>
                                <div class="tm-form-inner">
                                    <div class="tm-form-field">
                                        <input type="checkbox" name="checkout-terms"
                                            id="checkout-read-terms">
                                        <label for="checkout-read-terms">I have read and agree to the website
                                            terms and conditions</label>
                                    </div>
                                    <div class="tm-form-field">
                                        <button type="submit" class="tm-button ml-auto">Place Order</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!--// Checkout Area -->

</main>
<!--// Page Content -->
{% endblock content %}